#Introduction to TensorFlow

# 📘 TensorFlow Basics

TensorFlow is a powerful open-source library developed by Google for deep learning and numerical computation. It uses dataflow graphs and automatic differentiation to perform optimized computations.

Let's get started by learning how to use Tensors, which are the fundamental building blocks of TensorFlow.


##Installing and Importing TensorFlow

In [5]:
#!pip install tensorflow -q
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.20.0


## 📦 Tensors

Tensors are multi-dimensional arrays (like NumPy arrays). TensorFlow supports scalar (0D), vector (1D), matrix (2D), and higher dimensional tensors.

Let's see how to create and inspect them.


##Tensor Creation and Attributes

In [6]:
# Scalar
scalar = tf.constant(7)
print("Scalar:", scalar)

# Vector
vector = tf.constant([1.0, 2.0, 3.0])
print("Vector:", vector)

# Matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# Check shape and dtype
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)


Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Shape: (2, 2)
Data Type: <dtype: 'int32'>


## ➕ Tensor Operations

TensorFlow supports element-wise operations like addition, multiplication, matrix multiplication, etc.


##Tensor Arithmetic

In [7]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# Addition
print("Addition:\n", tf.add(a, b))

# Multiplication (element-wise)
print("Element-wise Multiplication:\n", tf.multiply(a, b))

# Matrix multiplication
print("Matrix Multiplication:\n", tf.matmul(a, b))


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# 🏗️ Building a Neural Network with TensorFlow (Keras)

We'll use `tf.keras`, a high-level API for building and training models. Let's train a simple neural network to classify digits using the MNIST dataset.


##Load Dataset and Normalize

In [8]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize to [0, 1]
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [9]:
print(x_train.shape)

(60000, 28, 28)


##Define a Model


In [10]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),  # Input layer
    tf.keras.layers.Dense(128, activation='relu'),  # Hidden layer
    tf.keras.layers.Dense(10, activation='softmax') # Output layer
])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


##Compile and Train

In [11]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9260 - loss: 0.2591
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9656 - loss: 0.1159
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9757 - loss: 0.0795
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9816 - loss: 0.0600
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9861 - loss: 0.0452


##Evaluate the Model

In [12]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print("\nTest accuracy :", test_acc)
print("\nTest loss :", test_loss)


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9788 - loss: 0.0710

Test accuracy : 0.9787999987602234

Test loss : 0.07098960876464844


#1. Understand the Basic Syntax and Operations (PyTorch)

# Introduction to PyTorch
## 🔥 PyTorch Basics

PyTorch is a popular open-source deep learning library developed by Facebook AI. It provides flexibility and speed through dynamic computation graphs and strong GPU support.

In this section, we'll start by exploring how PyTorch handles tensors and automatic differentiation.


##Installing and Importing PyTorch

In [13]:
# If you're in a notebook or Colab
!#pip install torch -q
import torch
print("PyTorch version:", torch.__version__)


PyTorch version: 2.11.0+cpu


##Creating and Inspecting Tensors
## 📦 Tensors in PyTorch

Tensors are multidimensional arrays, just like in NumPy. They're the building blocks of PyTorch and support operations like addition, multiplication, reshaping, etc.


##Tensor Creation and Properties

In [14]:
# Scalar
scalar = torch.tensor(5)
print("Scalar:", scalar)

# Vector
vector = torch.tensor([1.0, 2.0, 3.0])
print("Vector:", vector)

# Matrix
matrix = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Matrix:\n", matrix)

# Shape and data type
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)


Scalar: tensor(5)
Vector: tensor([1., 2., 3.])
Matrix:
 tensor([[1., 2.],
        [3., 4.]])
Shape: torch.Size([2, 2])
Data Type: torch.float32


## ➕ Tensor Operations

PyTorch supports common element-wise operations as well as matrix multiplication, reshaping, and broadcasting.


##Tensor Arithmetic

In [15]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Addition
print("Addition:\n", a + b)

# Element-wise multiplication
print("Element-wise Multiplication:\n", a * b)

# Matrix multiplication
print("Matrix Multiplication:\n", torch.matmul(a, b))


Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


# 🏗️ Building a Neural Network with PyTorch

Now let's build a simple neural network to classify digits from the MNIST dataset using `torch.nn` and `torch.optim`.


##Load and Normalize MNIST Dataset

In [24]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Transform: Normalize to [0, 1]
transform = transforms.ToTensor()

train_data = datasets.MNIST(root='data', train=True, download=True, transform=transform)
test_data = datasets.MNIST(root='data', train=False, download=True, transform=transform)

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)


##Define Neural Network

In [25]:
import torch.nn as nn
import torch.nn.functional as F

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(x.shape[0], -1)  # Flatten
        x = F.relu(self.fc1(x))
        return F.log_softmax(self.fc2(x), dim=1)

model = SimpleNN()


##Define Loss and Optimizer

In [26]:
import torch.optim as optim

criterion = nn.NLLLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


##Train the Model

In [27]:
epochs = 3
for epoch in range(epochs):
    for images, labels in train_loader:
        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


Epoch 1, Loss: 0.1438
Epoch 2, Loss: 0.1107
Epoch 3, Loss: 0.0666


##Evaluate Accuracy

In [28]:
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Test Accuracy: {correct / total * 100:.2f}%")


Test Accuracy: 96.64%


#3. Compare Similarities and Differences with TensorFlow


# PyTorch vs TensorFlow: Quick Comparison

| Feature                | PyTorch                               | TensorFlow                           |
|------------------------|----------------------------------------|--------------------------------------|
| Execution Mode         | Eager (Dynamic)                        | Eager (Static with option for Graph) |
| High-Level API         | `torch.nn`, `torch.optim`              | `tf.keras`                           |
| Dataset Loader         | `DataLoader`                           | `tf.data.Dataset`                    |
| Training Loop Style    | Mostly manual                          | `model.fit()` or manual              |
| Model Saving           | `torch.save()`                         | `model.save()` or `SavedModel`       |
| Visualization Tool     | TensorBoard (via `torch.utils.tensorboard`) | TensorBoard                    |
| Autograd Support       | Built-in via `autograd`                | `tf.GradientTape()`                  |

Both libraries are capable of building state-of-the-art models. Your choice depends on project needs and comfort with syntax.


--------------------------------------------------------------------------------

#Activity

Create two custom models, one with Tensorflow and the other with Pytorch.
The models should have

###  Model Architecture (Same for Both Frameworks)

| Layer Type         | Configuration                      |
|--------------------|-------------------------------------|
| Input Layer        | Flatten (28×28 → 784)              |
| Dense Layer 1      | 256 units, ReLU                    |
| Dropout Layer      | 30% (rate = 0.3)                   |
| Dense Layer 2      | 128 units, Tanh                    |
| Output Layer       | 10 units, Softmax (TF) / LogSoftmax (PT) |

###  Instructions

- Implement this architecture using `tf.keras.Sequential` in TensorFlow.
- Implement the same architecture using `torch.nn.Module` in PyTorch.
- Train both models for **5 epochs** using the **Adam optimizer** and an appropriate classification loss.
- Evaluate accuracy on the MNIST test set.


In [29]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("Is GPU available?", tf.config.list_physical_devices('GPU'))


TensorFlow version: 2.20.0
Is GPU available? []


In [30]:
# Load and preprocess MNIST
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)


(60000, 28, 28) (60000,) (10000, 28, 28) (10000,)


In [31]:
# Build the model — exact architecture from the table above
tf_model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),   # Input layer: 28x28 -> 784
    tf.keras.layers.Dense(256, activation='relu'),   # Dense Layer 1
    tf.keras.layers.Dropout(0.3),                    # Dropout 30%
    tf.keras.layers.Dense(128, activation='tanh'),   # Dense Layer 2
    tf.keras.layers.Dense(10, activation='softmax')  # Output layer (Softmax)
])

tf_model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 256)            │       200,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 235,146 (918.54 KB)

 Trainable params: 235,146 (918.54 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
# Compile: Adam optimizer + classification loss
tf_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train for 5 epochs
tf_history = tf_model.fit(
    x_train, y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.1
)


Epoch 1/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9160 - loss: 0.2789 - val_accuracy: 0.9710 - val_loss: 0.1027
Epoch 2/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9599 - loss: 0.1311 - val_accuracy: 0.9753 - val_loss: 0.0853
Epoch 3/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 11s 11ms/step - accuracy: 0.9694 - loss: 0.0990 - val_accuracy: 0.9782 - val_loss: 0.0711
Epoch 4/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.9739 - loss: 0.0820 - val_accuracy: 0.9808 - val_loss: 0.0676
Epoch 5/5
844/844 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step - accuracy: 0.9769 - loss: 0.0690 - val_accuracy: 0.9828 - val_loss: 0.0636


In [33]:
# Evaluate on the MNIST test set
tf_test_loss, tf_test_accuracy = tf_model.evaluate(x_test, y_test, verbose=0)
print(f"TensorFlow Test Accuracy: {tf_test_accuracy:.4f}")
print(f"TensorFlow Test Loss: {tf_test_loss:.4f}")


TensorFlow Test Accuracy: 0.9789
TensorFlow Test Loss: 0.0708


## Part 2 — PyTorch (`torch.nn.Module`)

In [34]:
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

print("PyTorch version:", torch.__version__)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


PyTorch version: 2.11.0+cpu
Using device: cpu


In [35]:
# Load MNIST (same dataset, PyTorch-native loader)
transform = transforms.ToTensor()

pt_train_data = datasets.MNIST(root='data', train=True, download=True, transform=transform)
pt_test_data = datasets.MNIST(root='data', train=False, download=True, transform=transform)

pt_train_loader = DataLoader(pt_train_data, batch_size=64, shuffle=True)
pt_test_loader = DataLoader(pt_test_data, batch_size=64, shuffle=False)


In [36]:
# Same architecture as the TensorFlow model above
class SimpleModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()                # Input layer: 28x28 -> 784
        self.fc1 = nn.Linear(784, 256)              # Dense Layer 1
        self.dropout = nn.Dropout(0.3)              # Dropout 30%
        self.fc2 = nn.Linear(256, 128)               # Dense Layer 2
        self.out = nn.Linear(128, 10)                # Output layer

    def forward(self, x):
        x = self.flatten(x)
        x = F.relu(self.fc1(x))                      # ReLU activation
        x = self.dropout(x)
        x = torch.tanh(self.fc2(x))                  # Tanh activation
        x = self.out(x)
        return F.log_softmax(x, dim=1)               # LogSoftmax output

pt_model = SimpleModel().to(device)
print(pt_model)


SimpleModel(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc1): Linear(in_features=784, out_features=256, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc2): Linear(in_features=256, out_features=128, bias=True)
  (out): Linear(in_features=128, out_features=10, bias=True)
)


In [37]:
# Adam optimizer + NLLLoss (pairs with LogSoftmax output, equivalent to
# categorical cross-entropy on the softmax probabilities)
optimizer = torch.optim.Adam(pt_model.parameters(), lr=0.001)
criterion = nn.NLLLoss()

start_time = time.time()
for epoch in range(5):
    pt_model.train()
    running_loss, num_batches = 0.0, 0
    for images, labels in pt_train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        output = pt_model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        num_batches += 1

    print(f"Epoch {epoch+1}/5 — avg loss: {running_loss/num_batches:.4f}")

print(f"\nPyTorch training time: {time.time() - start_time:.2f} sec")


Epoch 1/5 — avg loss: 0.2881
Epoch 2/5 — avg loss: 0.1266
Epoch 3/5 — avg loss: 0.0934
Epoch 4/5 — avg loss: 0.0780
Epoch 5/5 — avg loss: 0.0637

PyTorch training time: 75.73 sec


In [38]:
# Evaluate accuracy on the MNIST test set
pt_model.eval()
correct, total = 0, 0

with torch.no_grad():
    for images, labels in pt_test_loader:
        images, labels = images.to(device), labels.to(device)
        output = pt_model(images)
        predictions = output.argmax(dim=1)
        correct += (predictions == labels).sum().item()
        total += labels.size(0)

pt_test_accuracy = correct / total
print(f"PyTorch Test Accuracy: {pt_test_accuracy:.4f}")


PyTorch Test Accuracy: 0.9790


## Part 3 — Final Comparison

In [39]:
print("="*40)
print("Final Test Accuracy Comparison")
print("="*40)
print(f"TensorFlow : {tf_test_accuracy:.4f}")
print(f"PyTorch    : {pt_test_accuracy:.4f}")
print("="*40)


Final Test Accuracy Comparison
TensorFlow : 0.9789
PyTorch    : 0.9790
